### ISSUE TITLE
add SMS messaging option

### ISSUE THREAD

**Issue by andyczerwonka** [andyczerwonka/tyrion#170]
Rob Monck has asked for SMS notifications. There are situations where data coverage is very low and SMS would at the very least give them better accessibility.

### Details
1. New user profile page where users can select the method(s) for notifications.
2. User a service like [Twilio](https://www.twilio.com/sms) to send off the SMS messages

### Tasks
- [x] user profile CRUD api (6 hours)
- [x] user profile modal next to the logoff menu (8 hours)
- [ ] SMS notification (4 hours)
- [x] upgrade database to put in default email notification, SMS number and notification will be blank (1 hour)
- [x] 10 digit phone validation (1 hour)

**Comment by andyczerwonka** [comment]
My gut tells me this is a few days' work. Most of the work will come from setting up the CRUD around each users notification preference. That's one full day. Once that's done, it should be another day to get the Twilio account and start sending SMS.

12 hours.

**Comment by andyczerwonka** [comment]
https://www.twilio.com/help/faq/sms/what-is-alphanumeric-sender-id-and-how-do-i-get-started

**Comment by andyczerwonka** [comment]
https://youtu.be/d0DuoycKNU0

**Comment by andyczerwonka** [comment]
https://github.com/twilio/twilio-java

**Comment by andyczerwonka** [comment]
Notifications are complete, just waiting to see what the best account for sending SMS is. Right now we can use the local number.
