### ISSUE TITLE
Play Framework 2.5 Upgrade

### ISSUE THREAD

**Issue by andyczerwonka** [andyczerwonka/tyrion#180]
We're behind on Play and before I start to make the necessary changes to get the interval setting in and upgrade all the tests, I will need to update Play to 2.5.0. This is a step change release, so I'll have to deal with some of the deprecated libraries, particularly are the cryptography we use for session credentials.

### Tasks
- [x] upgrade sbt
- [x] upgrade Play
- [x] rewrite all tests using ScalaTest 3.0
- [x] replace crypto API
- [x] replace Global API
- [x] use DI or the application environment
- [x] replace Akka deprecations
- [x] fix logback - https://www.playframework.com/documentation/2.5.x/Migration25#Change-to-Logback-configuration
- [x] gzip and csrf filters

**Comment by andyczerwonka** [comment]
All tests ported. During the process I found a couple of bugs, plus all tests are now deterministic so while painful it was a useful exercise.

**Comment by laurentbrig** [comment]
That's great!

**Comment by andyczerwonka** [comment]
Done!!!!! See https://github.com/andyczerwonka/tyrion/wiki/Upgrade-to-Play-Framwork-2.5.x

**Comment by laurentbrig** [comment]
Now onto store and forward?
